vich_uploader:
    db_driver: orm
    mappings:
        user_image:
            uri_prefix: /images/utilisateurs
            upload_destination: '%kernel.project_dir%/public/images/utilisateurs'
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
