<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.udpuepO' shared service.

return $this->privates['.service_locator.udpuepO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\PartenaireController::partUserModif' => ['privates', '.service_locator.BSb3rX6', 'get_ServiceLocator_BSb3rX6Service.php', true],
    'App\\Controller\\PartenaireController::reguser' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\UtilisateurController::depot' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\UtilisateurController::partUserModif' => ['privates', '.service_locator.BSb3rX6', 'get_ServiceLocator_BSb3rX6Service.php', true],
    'App\\Controller\\UtilisateurController::register' => ['privates', '.service_locator.a1V7ZWg', 'get_ServiceLocator_A1V7ZWgService.php', true],
    'App\\Controller\\UtilisateurController::reguser' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\PartenaireController:partUserModif' => ['privates', '.service_locator.BSb3rX6', 'get_ServiceLocator_BSb3rX6Service.php', true],
    'App\\Controller\\PartenaireController:reguser' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\UtilisateurController:depot' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\UtilisateurController:partUserModif' => ['privates', '.service_locator.BSb3rX6', 'get_ServiceLocator_BSb3rX6Service.php', true],
    'App\\Controller\\UtilisateurController:register' => ['privates', '.service_locator.a1V7ZWg', 'get_ServiceLocator_A1V7ZWgService.php', true],
    'App\\Controller\\UtilisateurController:reguser' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
], [
    'App\\Controller\\PartenaireController::partUserModif' => '?',
    'App\\Controller\\PartenaireController::reguser' => '?',
    'App\\Controller\\RegistrationController::register' => '?',
    'App\\Controller\\UtilisateurController::depot' => '?',
    'App\\Controller\\UtilisateurController::partUserModif' => '?',
    'App\\Controller\\UtilisateurController::register' => '?',
    'App\\Controller\\UtilisateurController::reguser' => '?',
    'App\\Controller\\PartenaireController:partUserModif' => '?',
    'App\\Controller\\PartenaireController:reguser' => '?',
    'App\\Controller\\RegistrationController:register' => '?',
    'App\\Controller\\UtilisateurController:depot' => '?',
    'App\\Controller\\UtilisateurController:partUserModif' => '?',
    'App\\Controller\\UtilisateurController:register' => '?',
    'App\\Controller\\UtilisateurController:reguser' => '?',
]);
