<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHSNIXkY\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHSNIXkY/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerHSNIXkY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerHSNIXkY\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerHSNIXkY\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'HSNIXkY',
    'container.build_id' => '93061cc9',
    'container.build_time' => 1565104337,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHSNIXkY');
