<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXcjmOTR\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXcjmOTR/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXcjmOTR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXcjmOTR\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXcjmOTR\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XcjmOTR',
    'container.build_id' => 'a0f73087',
    'container.build_time' => 1567742440,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXcjmOTR');
