<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFkn9NFd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFkn9NFd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFkn9NFd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFkn9NFd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFkn9NFd\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Fkn9NFd',
    'container.build_id' => '4d763e15',
    'container.build_time' => 1565212241,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFkn9NFd');
