<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWleTMuI\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWleTMuI/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWleTMuI.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWleTMuI\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWleTMuI\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WleTMuI',
    'container.build_id' => '5e0dfc92',
    'container.build_time' => 1567380064,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWleTMuI');
